#!/bin/python

with open("example.cimg", "wb") as file:
    file.write(b"cIMG")
    file.write((1).to_bytes(8, "little"))
    file.write((62).to_bytes(8, "little"))
    file.write((14).to_bytes(4, "little"))
    file.write((62*14)*b"x")
